[package]
name = "policy-server"
version = "0.2.3"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.0"
itertools = "0.10.1"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.2.4" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.1.19" }
kubewarden-policy-sdk = "0.2.4"
lazy_static = "1.4.0"
clap = "2.33.3"
futures-util = "0.3.12"
kube = "0.64.0"
k8s-openapi = { version = "0.13.0", default-features = false, features = ["v1_22"] }
hyper-tls = "0.5.0"
hyper = { version = "0.14", features = ["full"] }
num_cpus = "1.13.0"
openssl = "0.10.32"
opentelemetry = { version = "0.16", default-features = false, features = ["metrics", "trace", "rt-tokio", "serialize"] }
opentelemetry-otlp = { version = "0.9.0", features = ["metrics", "tonic"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.15"
tokio-native-tls = "0.3.0"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version= "0.2", features = ["fmt"] }
tracing-futures = "0.2"
tracing-opentelemetry = "0.15.0"

[patch.crates-io]
# Forcing base64ct to version 1.1.1 given that version 1.2.0 has been
# bumped to use Rust 2021 edition. When we see is time, we can bump as
# well, but for now, pin to 1.1.1 that is bound to edition 2018.
base64ct = { git = "https://github.com/RustCrypto/formats.git", tag = "base64ct/v1.1.1" }