[package]
name = "policy-server"
version = "0.1.2"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.0"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.1.9" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.1.10" }
kubewarden-policy-sdk = "0.2.0"
clap = "2.33.3"
futures-util = "0.3.12"
kube = "0.51.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
hyper-tls = "0.5.0"
hyper = { version = "0.14", features = ["full"] }
num_cpus = "1.13.0"
openssl = "0.10.32"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.15"
tokio-native-tls = "0.3.0"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version= "0.2", features = ["fmt"] }
tracing-futures = "0.2"

[dependencies.cranelift-codegen]
# Report: https://github.com/kubewarden/policy-server/issues/67
version = "^0.73.1"

[dependencies.raw-cpuid]
# Report: https://github.com/kubewarden/policy-server/issues/68
version = "^9.0.0"