# This is the minimal configuration to start a OpenTelemetry collector
# that collects traces via the otlp protocol, and then sends them via
# batches to a central jaeger collector
#
# A simple otel-collector instance can be started in this way:
#
#   docker run --rm -p 4317:4317 \
#     -v `pwd`/otel-collector-minimal-config.yaml:/etc/otel/config.yaml:ro \
#     otel/opentelemetry-collector-dev:latest
#

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  jaeger:
    # TODO: change the IP address with the IP/FQDN of your jaeger endpoint
    endpoint: "192.168.122.77:14250"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
