[package]
name = "burrego"
version = "0.1.0"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.28.0"
anyhow = "1.0.40"
serde_json = "1.0.64"
clap = "2.33.3"
gtmpl = "0.7.0"
lazy_static = "1.4.0"
