# permissions for end users to view clusteradmissionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusteradmissionpolicy-viewer-role
rules:
- apiGroups:
  - kubewarden.suse.com
  resources:
  - clusteradmissionpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubewarden.suse.com
  resources:
  - clusteradmissionpolicies/status
  verbs:
  - get
