# permissions for end users to edit clusteradmissionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusteradmissionpolicy-editor-role
rules:
- apiGroups:
  - kubewarden.suse.com
  resources:
  - clusteradmissionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubewarden.suse.com
  resources:
  - clusteradmissionpolicies/status
  verbs:
  - get
