# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/chimera.suse.com_admissionpolicies.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# +kubebuilder:scaffold:crdkustomizewebhookpatch
- patches/cainjection_in_admissionpolicies.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch
