[package]
name = "policy-evaluator"
version = "0.1.15"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13.0"
hyper = { version = "0.14" }
json-patch = "0.2.6"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
kube = "0.51.0"
kubewarden-policy-sdk = "0.2.2"
lazy_static = "1.4.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "^1" }
tracing = "0.1"
tracing-futures = "0.2"
validator = { version = "0.13", features = ["derive"] }
wapc = "0.10.1"
wasmparser = "0.78.0"

# TODO: point back to the official wasmtime-provider crate once a new release is
# tagged. This is required to grab the patch of a wasmtime security issue
# wasmtime-provider = "0.0.3"
wasmtime-provider = { git = "https://github.com/flavio/wasmtime-provider.git", branch = "update-wasmtime" }

[dev-dependencies]
assert-json-diff = "2.0.1"
