name: Build container image, sign it, and generate SBOMs

on:
  workflow_call:
    outputs:
      digest:
        description: "Container image digest"
        value: ${{jobs.build.outputs.digest}}

  push:
    branches:
      - "main"
      - "feat-**"

jobs:
  build:
    name: Build container image
    uses: ./.github/workflows/container-image.yml
    permissions:
      packages: write
    with:
      push-image: true

  sign:
    name: Sign container image
    needs: build
    uses: ./.github/workflows/sign-image.yml
    permissions:
      packages: write
      id-token: write
    with:
      image-digest: ${{ needs.build.outputs.digest }}

  sbom:
    name: Generate SBOM and push them to OCI registry
    needs: build
    uses: ./.github/workflows/sbom.yml
    permissions:
      packages: write
      id-token: write
    with:
      image-digest: ${{ needs.build.outputs.digest }}
