name: Build container image every change.

on:
  workflow_call:
    outputs:
      digest:
        description: "Container image digest"
        value: ${{jobs.build.outputs.digest}}

  push:
    branches:
      - "main"
      - "feat-**"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/container-image.yml
    permissions:
      packages: write
    with:
      push-image: true

  sbom:
    name: SBOM
    needs: build
    uses: ./.github/workflows/sbom.yml
    permissions:
      packages: write
      id-token: write
    with:
      image-digest: ${{ needs.build.outputs.digest }}
