name: kubewarden-controller release
on:
  push:
    tags:
    - 'v*'
jobs:
  ci:
    uses: kubewarden/kubewarden-controller/.github/workflows/ci.yml@main
  release:
    name: Create release
    needs:
      - ci
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release kubewarden-controller ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
