name: kubewarden-controller release
on:
  push:
    tags:
    - 'v*'

# Declare default permissions as read only.
permissions: read-all

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions: read-all

  build:
    name: Build container image and SBOMs
    uses: ./.github/workflows/container-build.yml
    permissions:
      id-token: write
      packages: write

  crds:
    name: Build CRDs
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate CRDs
        run: |
          make generate-crds
          tar -czf CRDS.tar.gz -C generated-crds $(ls generated-crds)
      -
        name: Upload CRDs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CRDS
          path: CRDS.tar.gz

  release:
    name: Create release

    needs:
      - ci
      - crds
      - build

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Retrieve tag name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo ${{ github.ref_name }}) >> $GITHUB_ENV

      - name: Get latest release tag
        id: get_last_release_tag
        uses: actions/github-script@v6
        with:
          script: |
            let release = await github.rest.repos.getLatestRelease({
               owner: context.repo.owner,
               repo: context.repo.repo,
            });

            if (release.status  === 200 ) {
              core.setOutput('old_release_tag', release.data.tag_name)
              return
            }
            core.setFailed("Cannot find latest release")

      - name: Get release ID from the release created by release drafter
        uses: actions/github-script@v6
        with:
          script: |
            let releases = await github.rest.repos.listReleases({
               owner: context.repo.owner,
               repo: context.repo.repo,
            });
            for (const release of releases.data) {
              if (release.draft) {
                      core.info(release)
                      core.exportVariable('RELEASE_ID', release.id)
                      return
              }
            }
            core.setFailed(`Draft release not found`)

      - name: Download SBOM artifact
        uses: actions/download-artifact@v3
        with:
          name: sbom

      - name: Download CRDs artifact
        uses: actions/download-artifact@v3
        with:
          name: CRDS

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload release assets
        id: upload_release_assets
        uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let files = [
              'kubewarden-controller-sbom-amd64.spdx',
              'kubewarden-controller-sbom-amd64.spdx.cert',
              'kubewarden-controller-sbom-amd64.spdx.sig',
              'kubewarden-controller-sbom-arm64.spdx',
              'kubewarden-controller-sbom-arm64.spdx.cert',
              'kubewarden-controller-sbom-arm64.spdx.sig',
              "CRDS.tar.gz"]
            const {RELEASE_ID} = process.env

            for (const file of files) {
              let file_data = fs.readFileSync(file);

              let response = await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: `${RELEASE_ID}`,
                name: file,
                data: file_data,
              });
              // store the crds asset id used it in the helm chart update
              if (file === "CRDS.tar.gz") {
                core.setOutput('crds_asset_id', response.data.id)
              }
            }

      - name: Publish release
        uses: actions/github-script@v6
        with:
          script: |
            const {RELEASE_ID} = process.env
            const {TAG_NAME} = process.env
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: `${RELEASE_ID}`,
              draft: false,
              tag_name: `${TAG_NAME}`,
              name: `${TAG_NAME}`,
              prerelease: `${{ contains(github.event.workflow_run.head_branch, '-alpha') || contains(github.event.workflow_run.head_branch, '-beta') || contains(github.event.workflow_run.head_branch, '-rc') }}`
            });

      - name: Trigger chart update
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          repository: "${{github.repository_owner}}/helm-charts"
          event-type: update-chart
          client-payload: '{"version": "${{ github.ref_name }}", "oldVersion": "${{ steps.get_last_release_tag.outputs.old_release_tag }}", "repository": "${{ github.repository }}", "crds_asset_id": "${{steps.upload_release_assets.outputs.crds_asset_id}}"}'
