name: kubewarden-controller release
on:
  push:
    tags:
    - 'v*'

# Declare default permissions as read only.
permissions: read-all

jobs:
  ci:
    uses: kubewarden/kubewarden-controller/.github/workflows/ci.yml@main
  container-build:
    uses: kubewarden/kubewarden-controller/.github/workflows/container-build.yml@main
  release:
    permissions:
      id-token: write
      contents: write
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - ci
      - container-build
    steps:
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install the bom command
        shell: bash
        run: go install sigs.k8s.io/bom/cmd/bom@v0.2.2

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve tag name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo ${{ github.ref }} | sed -e "s|refs/tags/||") >> $GITHUB_ENV

      - name: Create SBOM file
        shell: bash
        run: |
          bom generate -n https://kubewarden.io/kubewarden.spdx \
            --image "ghcr.io/${{github.repository_owner}}/kubewarden-controller@${{ needs.container-build.outputs.digest }}" \
            . > kubewarden-controller-sbom.spdx

      - name: Sign BOM file
        run: |
          cosign sign-blob --output-certificate kubewarden-controller-sbom.spdx.cert \
            --output-signature kubewarden-controller-sbom.spdx.sig \
            kubewarden-controller-sbom.spdx
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release kubewarden-controller ${{ env.TAG_NAME }}
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
          files: |
            kubewarden-controller-sbom.spdx
            kubewarden-controller-sbom.spdx.cert
            kubewarden-controller-sbom.spdx.sig
