name: ShellCheck
on:
  push:
    paths:
      - "scripts/**"
  pull_request:
    paths:
      - "scripts/**"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: shellcheck $(find scripts/ -name '*.sh')
