[advisories]
ignore = [
  "RUSTSEC-2020-0071", # `time` localtime_r segfault -- https://rustsec.org/advisories/RUSTSEC-2020-0071
                       # This vulnerability is currently not affecting chrono 0.4.20+
                       # See https://github.com/chronotope/chrono/issues/602
                       # Chrono 0.5 will upgrade this depependency, but this will lead
                       # to API breakages.
                       #
                       # This is a transitive depependency
  "RUSTSEC-2021-0146", # This is about `twoway` not being maintained anymore
                       # This is a transitive dependency of `multipart`, which is
                       # a dependency of `warp`. The `multipart` project has been
                       # archived in Feb 2023. This is the issue made against
                       # `warp` asking for the removal of the `multipart` dependency
                       # https://github.com/seanmonstar/warp/issues/1023
  "RUSTSEC-2023-0028", # This is about `buf_redux` not being maintained anymore
                       # This is a transitive dependency of `multipart`, which is
                       # a dependency of `warp`. The `multipart` project has been
                       # archived in Feb 2023. This is the issue made against
                       # `warp` asking for the removal of the `multipart` dependency
                       # https://github.com/seanmonstar/warp/issues/1023
  "RUSTSEC-2021-0147", # This is about "daemonize" being unmaintained.
                       # This is a feature that we use only when doing e2e tests
  "RUSTSEC-2020-0168", # This is about "mach" being unmaintained.
                       # This is a transitive dependency of wasmtime. This is
                       # being tracked upstream via https://github.com/bytecodealliance/wasmtime/issues/6000
]
