apiVersion: chimera.suse.com/v1alpha1
kind: AdmissionPolicy
metadata:
  name: privileged-pods
spec:
  module: registry://ghcr.io/chimera-kube/policies/pod-privileged:v0.1.0
  resources:
  - pods
  operations:
  - CREATE
  - UPDATE
  settings:
    trusted_users:
    - alice
