[package]
name = "kwctl"
description = "Tool to manage Kubewarden policies"
version = "0.1.0"
authors = [
        "Flavio Castelli <fcastelli@suse.com>",
        "Rafael Fernández López <rfernandezlopez@suse.com>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.33.3"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", branch = "settings-options" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.1.0" }
serde_json = "1.0"
serde_yaml = "0.8.17"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "^1", features = ["full"] }