[package]
name = "policy-fetcher"
version = "0.2.3"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-std = "1.9.0"
async-stream = "0.3.0"
async-trait = "0.1.50"
base64 = "0.13.0"
directories = "3.0.2"
lazy_static = "1.4.0"
#oci-distribution = "0.6"
# Pinned git revision to be replaced with a tag when something greater than v0.8.0 is tagged
oci-distribution = { git = "https://github.com/krustlet/oci-distribution", rev = "96f19570e7", default-features = false, features = ["rustls-tls"] }
reqwest = { version = "0.11.3", default-features = false, features = ["rustls-tls"] }
rustls = "0.19.1"
serde_json = "1.0.64"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.15"
sha2 = "0.9.5"
sigstore = { git = "https://github.com/kubewarden/sigstore-rs", default-features = false, features = ["rustls-tls"], branch = "not-yet-merged-patches" }
tracing = "0.1.29"
url = "2.2.0"
walkdir = "2"

[dev-dependencies]
rstest = "0.11.0"
tempfile = "3.2.0"
textwrap = "0.11.0"