# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  tests: true
  timeout: 10m

issues:
  exclude-rules:
    - linters:
        - funlen
      # Disable 'funlen' linter for test functions.
      # It's common for table-driven tests to be more than 60 characters long
      source: "^func Test"
    - path: internal/pkg/admission/policy-server-error.go
      linters:
        - deadcode
        - unused
    - path: internal/pkg/admissionregistration/cert.go
      linters:
        - gocritic
    - path: internal/pkg/admission/validating-webhook.go
      linters:
        - dupl
    - path: internal/pkg/admission/mutating-webhook.go
      linters:
        - dupl

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godot
    - goerr113
    - gofumpt
    - gomnd
    - maligned
    - nlreturn
    - paralleltest
    - testpackage
    - wsl
    - lll # long lines
    # https://github.com/golangci/golangci-lint/issues/541
    - interfacer
    # TODO: enable once we can set some exceptions
    - funlen

linters-settings:
  cyclop:
    max-complexity: 13
  nestif:
    min-complexity: 8
